import os
import json
import faiss
from fastapi import APIRouter, UploadFile, File, HTTPException

# Import our custom modules
from app.models.schemas import QueryRequest
from app.services.document_parser import process_pdf
from app.services.vector_db import build_and_save_vector_db, get_embedding
from app.services.llm_engine import call_groq_with_fallback

router = APIRouter()

@router.post("/upload")
async def upload_document(file: UploadFile = File(...)):
    file_path = f"uploads/{file.filename}"
    with open(file_path, "wb") as f:
        f.write(await file.read())
        
    try:
        chunks = process_pdf(file_path)
        build_and_save_vector_db(chunks)
        return {"status": "success", "message": f"Successfully processed {len(chunks)} data chunks."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(file_path):
            os.remove(file_path)

@router.post("/query")
async def query_assistant(request: QueryRequest):
    question = request.question
    
    if not os.path.exists("db/vector_db.faiss") or not os.path.exists("db/chunks.json"):
        raise HTTPException(status_code=400, detail="No database found. Please upload a PDF first.")
        
    index = faiss.read_index("db/vector_db.faiss")
    with open("db/chunks.json", "r") as f:
        medical_chunks = json.load(f)
        
    # ==========================================
    # 1. THE AGENTIC ROUTER (LANE DECISION)
    # ==========================================
    router_prompt = """You are a medical query routing classifier used in a clinical AI pipeline.

Your task is to classify the USER'S QUESTION into ONE of the following categories based on intent:

REPORT:
The user is asking about interpretation, meaning, status, or implications of a specific lab value, medical test result, or measurement mentioned in their personal report (e.g. Hemoglobin, LDL, WBC count, Platelets, etc.)

GENERAL:
The user is asking for general medical knowledge, lifestyle advice, diet suggestions, precautions, causes, or definitions WITHOUT referencing any personal lab value or report measurement.

HYBRID:
The user is asking about BOTH:
(A) a specific lab/test value from their report
AND
(B) general medical advice such as precautions, diet, lifestyle, treatment suggestions, or next steps.

CRITICAL RULES:
- If ANY personal lab value is mentioned AND advice is requested → HYBRID
- If ANY report metric is interpreted → REPORT
- If NO report metric is mentioned → GENERAL
- When uncertain → choose HYBRID

Respond with ONLY one word:
REPORT
GENERAL
HYBRID

No punctuation. No explanation."""

    router_messages = [
        {"role": "system", "content": router_prompt},
        {"role": "user", "content": f"Question: {question}"}
    ]
    route_decision = call_groq_with_fallback(router_messages, temperature=0.0, max_tokens=10).strip().upper()
    
    # ==========================================
    # 2. DIRECT TRAFFIC DOWN THE 3 LANES
    # ==========================================
    
    if "HYBRID" in route_decision:
        question_array = get_embedding(question)
        distances, indices = index.search(question_array, k=1)
        retrieved_text = medical_chunks[indices[0][0]]
        
        hybrid_prompt = """You are an AI medical assistant operating in a Retrieval-Augmented Generation (RAG) system.

Step 1:
Answer the user's question about their lab results using ONLY the provided Lab Report Text.
If the requested lab value or information is not present, clearly state that it was not found in the report.

Step 2:
If the user asks for general precautions, diet advice, or next steps, provide general educational guidance based on established medical knowledge.

RULES:
- Do NOT diagnose any condition.
- Do NOT confirm presence of disease.
- Use cautious language such as "may indicate" or "can be associated with".
- Do NOT assume or invent missing lab values.
- Clearly separate lab interpretation and general advice in your response.

Always conclude your response with:
"This information is generated by an AI system and should not be considered a clinical diagnosis."
"""
        messages = [
            {"role": "system", "content": hybrid_prompt},
            {"role": "user", "content": f"Lab Report Text:\n{retrieved_text}\n\nQuestion: {question}"}
        ]
        answer = call_groq_with_fallback(messages, temperature=0.2)
        
    elif "REPORT" in route_decision:
        question_array = get_embedding(question)
        distances, indices = index.search(question_array, k=1)
        retrieved_text = medical_chunks[indices[0][0]]
        
        report_prompt = """You are a medical assistant. Answer the user's question using ONLY the provided lab report text. If the lab report does not contain the relevant metrics to answer the question, explicitly state that the information is missing. Do not guess."""
        
        messages = [
            {"role": "system", "content": report_prompt},
            {"role": "user", "content": f"Lab Report Text:\n{retrieved_text}\n\nQuestion: {question}"}
        ]
        answer = call_groq_with_fallback(messages, temperature=0.1)
        
    else:
        # GENERAL LANE
        general_prompt = """You are a general medical knowledge assistant.

You must:
- Provide educational, non-diagnostic medical information.
- Use cautious language such as "may", "can", or "might indicate".
- Provide only general lifestyle or precautionary suggestions when appropriate.

You must NOT:
- Confirm or diagnose any disease or condition.
- Prescribe medications.
- Provide treatment plans.
- Interpret personal lab results or measurements.

Always conclude your response with:
"This information is provided by an AI system for general educational purposes and should not be considered a clinical diagnosis."
"""
        messages = [
            {"role": "system", "content": general_prompt},
            {"role": "user", "content": question}
        ]
        answer = call_groq_with_fallback(messages, temperature=0.3)
        
    return {
        "route_taken": route_decision,
        "answer": answer
    }